//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS.Repository.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBatDongSanEntities : DbContext
    {
        public dbBatDongSanEntities()
            : base("name=dbBatDongSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Criteria> Criteria { get; set; }
        public virtual DbSet<DetailProject> DetailProject { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<GroupCriteria> GroupCriteria { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Like> Like { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Save> Save { get; set; }
        public virtual DbSet<TypeProject> TypeProject { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
