//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long ID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> CommentID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Project Project { get; set; }
    }
}
